switchtolayout;
z_span = 0.3e-6; ## theight
z_span_cladding = 2e-6;
z_span_substrate = 1.2e-6;
etch = 5e-6;
setnamed('Input Extensions::rect bend up','z span',z_span);
setnamed('cladding','z min',z_span/2);
setnamed('cladding','z max',z_span/2 + z_span_cladding);
setnamed('substrate','z max',-z_span/2);
setnamed('substrate','z min',-z_span/2 - z_span_substrate);
setnamed('rectangle','z max',-z_span/2 - z_span_substrate);
setnamed('rectangle','z min',-z_span/2 - z_span_substrate - etch);